### ISSUE TITLE
Support LLVM 7.0.1 >

### ISSUE THREAD

**Issue by Member1221** [MoritzMaxeiner/llvm-d#26] opened 2019-04-09 18:23 UTC
There has been quite a few version releases since 7.0.0, and i'm getting missing symbol errors with LLVM 7.0.1 (which is in the arch linux repos)

Could llvm-d be updated to support newer LLVM releases?

**Comment by MoritzMaxeiner** [comment] 2019-04-09 20:31
It certainly could and I welcome pull requests for it akin to #24.
W.r.t. `7.0.1` in particular, AFAIK LLVM [observes API compatibility for patch releases](http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html), thus missing symbol errors indicate a bug somewhere:
- `llvm-d`'s support for LLVM `7.0.0` is incomplete (Open another issue here to track that with as detailed steps as feasible on how to reproduce the issue)
- `LLVM` broke API compatibility from `7.0.0` to `7.0.1` (Open an issue upstream with the LLVM people)
- Something in your use of LLVM and llvm-d is wrong (linking against / loading the wrong (shared) library, e.g.)

If you're inclined to write a PR, do note that when adding support for another major version (like 8), https://github.com/MoritzMaxeiner/llvm-d/blob/v2.4.1/tools/get-targets is helpful in determining whether the new release added or removed backend targets.

**Comment by Member1221** [comment] 2019-04-09 21:20
The missing symbols seem to be related to link-time-optimization

**Comment by MoritzMaxeiner** [comment] 2019-04-09 23:09
> The missing symbols seem to be related to link-time-optimization

Of LLVM itself? If it makes symbols (officially) exposed by the LLVM C API disappear, I'd consider that an LLVM bug violating their API compatibility.

**Comment by MoritzMaxeiner** [comment] 2019-04-24 21:17
@Member1221 Any new information you can provide, such as (minimal) steps to reproduce?

**Comment by Member1221** [comment] 2019-04-24 23:24
Sorry, been very busy as of late. Will look in to it ASAP.

**Comment by MoritzMaxeiner** [comment] 2019-04-25 10:03
No rush, I just wanted to ascertain if this issue needed to remain open (it does).

**Comment by Member1221** [comment] 2019-04-25 15:38
The following output gets output in to stdout during startup of my application
```
Attempting to bind to LLVM...
Missing LLVM symbol: llvm_create_optimizer
Missing LLVM symbol: llvm_destroy_optimizer
Missing LLVM symbol: llvm_read_object_file
Missing LLVM symbol: llvm_optimize_modules
Missing LLVM symbol: lto_get_version
Missing LLVM symbol: lto_get_error_message
Missing LLVM symbol: lto_module_is_object_file
Missing LLVM symbol: lto_module_is_object_file_for_target
Missing LLVM symbol: lto_module_has_objc_category
Missing LLVM symbol: lto_module_is_object_file_in_memory
Missing LLVM symbol: lto_module_is_object_file_in_memory_for_target
Missing LLVM symbol: lto_module_create
Missing LLVM symbol: lto_module_create_from_memory
Missing LLVM symbol: lto_module_create_from_memory_with_path
Missing LLVM symbol: lto_module_create_in_local_context
Missing LLVM symbol: lto_module_create_in_codegen_context
Missing LLVM symbol: lto_module_create_from_fd
Missing LLVM symbol: lto_module_create_from_fd_at_offset
Missing LLVM symbol: lto_module_dispose
Missing LLVM symbol: lto_module_get_target_triple
Missing LLVM symbol: lto_module_set_target_triple
Missing LLVM symbol: lto_module_get_num_symbols
Missing LLVM symbol: lto_module_get_symbol_name
Missing LLVM symbol: lto_module_get_symbol_attribute
Missing LLVM symbol: lto_module_get_linkeropts
Missing LLVM symbol: lto_codegen_set_diagnostic_handler
Missing LLVM symbol: lto_codegen_create
Missing LLVM symbol: lto_codegen_create_in_local_context
Missing LLVM symbol: lto_codegen_dispose
Missing LLVM symbol: lto_codegen_add_module
Missing LLVM symbol: lto_codegen_set_debug_model
Missing LLVM symbol: lto_codegen_set_pic_model
Missing LLVM symbol: lto_codegen_set_cpu
Missing LLVM symbol: lto_codegen_set_assembler_path
Missing LLVM symbol: lto_codegen_set_assembler_args
Missing LLVM symbol: lto_codegen_add_must_preserve_symbol
Missing LLVM symbol: lto_codegen_write_merged_modules
Missing LLVM symbol: lto_codegen_compile
Missing LLVM symbol: lto_codegen_compile_to_file
Missing LLVM symbol: lto_codegen_optimize
Missing LLVM symbol: lto_codegen_compile_optimized
Missing LLVM symbol: lto_api_version
Missing LLVM symbol: lto_codegen_debug_options
Missing LLVM symbol: lto_initialize_disassembler
Missing LLVM symbol: lto_codegen_set_should_internalize
Missing LLVM symbol: lto_codegen_set_should_embed_uselists
Missing LLVM symbol: thinlto_create_codegen
Missing LLVM symbol: thinlto_codegen_dispose
Missing LLVM symbol: thinlto_codegen_add_module
Missing LLVM symbol: thinlto_codegen_process
Missing LLVM symbol: thinlto_module_get_num_objects
Missing LLVM symbol: thinlto_module_get_object
Missing LLVM symbol: thinlto_module_get_num_object_files
Missing LLVM symbol: thinlto_module_get_object_file
Missing LLVM symbol: thinlto_codegen_set_pic_model
Missing LLVM symbol: thinlto_codegen_set_cache_dir
Missing LLVM symbol: thinlto_codegen_set_cache_pruning_interval
Missing LLVM symbol: thinlto_codegen_set_final_cache_size_relative_to_available_space
Missing LLVM symbol: thinlto_codegen_set_cache_entry_expiration
Missing LLVM symbol: thinlto_codegen_set_savetemps_dir
Missing LLVM symbol: thinlto_set_generated_objects_dir
Missing LLVM symbol: thinlto_codegen_set_cpu
Missing LLVM symbol: thinlto_codegen_disable_codegen
Missing LLVM symbol: thinlto_codegen_set_codegen_only
Missing LLVM symbol: thinlto_debug_options
Missing LLVM symbol: lto_module_is_thinlto
Missing LLVM symbol: thinlto_codegen_add_must_preserve_symbol
Missing LLVM symbol: thinlto_codegen_add_cross_referenced_symbol
Missing LLVM symbol: thinlto_codegen_set_cache_size_bytes
Missing LLVM symbol: thinlto_codegen_set_cache_size_files
Missing LLVM symbol: LLVMCreateOprofileJITEventListener
LLVM was bound to successfully!
```

The code that binds LLVM
```d
shared static this() {
    writeln("Attempting to bind to LLVM...");
    LLVM.load("libLLVM.so");
    if (!LLVM.loaded) {
        stderr.writeln("Failed to bind to LLVM! Try installing LLVM or using the built-in VM (which has slower performance)");
    } else {
        writeln("LLVM was bound to successfully!");
    }
}
```

**Comment by MoritzMaxeiner** [comment] 2019-04-25 16:38
> arch repositories
To be certain: That means you are using Archlinux?
> The code that binds LLVM
Thanks, could you provide a minimal working example, i.e. full content of one D file that produces this behavior as well as the exact command line options with which you compiled it (and the D compiler you used, as well as its version)?

**Comment by Member1221** [comment] 2019-04-26 14:34
Yes, Arch Linux, but i've also seen this issue on Linux Mint.


A quick example dub project where it occurs.
```json
{
	"authors": [
		"blablabla"
	],
	"copyright": "Copyright © 2019, blablabla",
	"dependencies": {
		"llvm-d": "~>2.4.1"
	},
	"versions": ["LLVM_Load"],
	"description": "A minimal D application.",
	"license": "proprietary",
	"name": "q"
}
```

```d
import std.stdio;
import llvm;

void main() {
    LLVM.load("libLLVM.so");
    // ... Code goes here ...
}
```

**Comment by MoritzMaxeiner** [comment] 2019-04-26 15:57
One more thing: Which compiler are you using (dmd,ldc,gdc,something else) and which version of that compiler?

**Comment by Member1221** [comment] 2019-04-26 16:15
DMD64 D Compiler v2.085.1

**Comment by MoritzMaxeiner** [comment] 2019-04-27 14:06
Okay, so there's two issues a play here:
1. LLVM 2.4+ has a bug where the headers contain declarations for the following functions, but their implementations where removed:
   - `llvm_create_optimizer`
   - `llvm_destroy_optimizer`
   - `llvm_read_object_file`
   - `llvm_optimize_modules`
    Since llvm-d requires at least LLVM 3.1 I'm going to remove these entirely, subject to conditional readdition if and when upstream chooses to fix this. Since you originally discovered this issue, I suggest you report it to them at https://bugs.llvm.org.
2. `LLVMCreateOProfileJITEventListener` was added in LLVM 7, but the declaration for it had a typo an was declared as `LLVMCreateOprofileJITEventListener`. Since when updating llvm-d people generally just `diff -u` the llvm-c header and look for declaration changes, this snuck in. It's both an llvm upstream bug (one they fixed with the recent release of LLVM 8), but also an llvm-d bug we can easily work around on Linux at least, since we don't actually use the C declarations but interface via the C ABI (which uses the symbol names from the implementation); can't test other platforms at the moment.
3. All the lto and thinlto symbols actually reside in libLTO, not in libLLVM. I'm still thinking about how to solve this, but I'm currently partial to just take a list of shared objects when dynamically loading and check them one by one.

**Comment by MoritzMaxeiner** [comment] 2019-04-27 15:28
The issues mentioned above should be addressed by:
1. 47ca77e994464a1cc1837954180c9177a9cc8206
2. ccfa8a76c38f215bc7d40e3ddfb49da721c87a87
3. 25f3675c24eb7273b7c3dbbd923510dcfb5de7f2
Do note that in order to not get notices about missing lto/thinlto symbols you'll need to properly load the `LTO` library in addition to the standard `LLVM` library, e.g. like so:
```
LLVM.load("libLLVM.so", "libLTO.so");
```
Autoloading / loading via `LLVM.load()` should work provided the name of the latter library in yout system sans platform specific stuff is `LTO`.

**Comment by Member1221** [comment] 2019-04-27 15:49
I'm not using LTO either way, so make it togglable?

**Comment by MoritzMaxeiner** [comment] 2019-04-27 16:17
> I'm not using LTO either way, so make it togglable?

Don't load the LTO library then. Those missing symbol messages are warnings that are only visible in debug mode.

**Comment by Member1221** [comment] 2019-04-27 17:17
imo it should only show warnings if you specifically decide to load the LTO library, otherwise it might seem like to users that there's a bug with the application.

**Comment by MoritzMaxeiner** [comment] 2019-04-27 17:59
> it might seem like to users that there's a bug with the application.

I don't see how that's possible unless you distribute debug mode builds of your application - in which case: Why aren't you distributing release builds?

> imo it should only show warnings if you specifically decide to load the LTO library

Doing so would require hard coding a mapping of function pointer to shared library that would have to be updated with each LLVM release and also take into account that LLVM itself may be split into multiple shared libraries. That's a lot of extra complexity I'm not interested in tbh.

I've tested the commits and AFAICT this particular issue is solved.

**Closed by MoritzMaxeiner** 2019-04-27 17:59 UTC

**Comment by Member1221** [comment] 2019-04-27 18:10
Okay, fair nuff. Thanks for the help!
